### ISSUE TITLE
Configure error cannot find install-sh

### ISSUE THREAD

**Issue by nscott32** [dpayne/ncmpcpp-colorful#1]
I have a configure error saying configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.." despite that I am in the directory ncmpcpp-colorfull and the file exists.

**Comment by dpayne** [comment]
How are you running it. The compilation procedure should be

./autogen.sh --enable-clock --enable-outputs --enable-visualizer
make
sudo make install

Also this project is more of a side project for myself. My color changes have been merged and improved upon in the master branch here https://github.com/arybczak/ncmpcpp.
